export const countriesData = [
  {
    code: "AF",
    flag: "https://restcountries.eu/data/afg.svg",
    name: "Afghanistan",
    dialling_code: "+93",
  },
  {
    code: "AL",
    flag: "https://restcountries.eu/data/alb.svg",
    name: "Albania",
    dialling_code: "+355",
  },
  {
    code: "DZ",
    flag: "https://restcountries.eu/data/dza.svg",
    name: "Algeria",
    dialling_code: "+213",
  },
  {
    code: "AS",
    flag: "https://restcountries.eu/data/asm.svg",
    name: "American Samoa",
    dialling_code: "+1",
  },
  {
    code: "AD",
    flag: "https://restcountries.eu/data/and.svg",
    name: "Andorra",
    dialling_code: "+376",
  },
  {
    code: "AO",
    flag: "https://restcountries.eu/data/ago.svg",
    name: "Angola",
    dialling_code: "+244",
  },
  {
    code: "AI",
    flag: "https://restcountries.eu/data/aia.svg",
    name: "Anguilla",
    dialling_code: "+43",
  },
  {
    code: "AG",
    flag: "https://restcountries.eu/data/atg.svg",
    name: "Antigua and Barbuda",
    dialling_code: "+1",
  },
  {
    code: "AR",
    flag: "https://restcountries.eu/data/arg.svg",
    name: "Argentina",
    dialling_code: "+54",
  },
  {
    code: "AM",
    flag: "https://restcountries.eu/data/arm.svg",
    name: "Armenia",
    dialling_code: "+374",
  },
  {
    code: "AW",
    flag: "https://restcountries.eu/data/abw.svg",
    name: "Aruba",
    dialling_code: "+297",
  },
  {
    code: "AU",
    flag: "https://restcountries.eu/data/aus.svg",
    name: "Australia",
    dialling_code: "+61",
  },
  {
    code: "AZ",
    flag: "https://restcountries.eu/data/aze.svg",
    name: "Azerbaijan",
    dialling_code: "+994",
  },
  {
    code: "BS",
    flag: "https://restcountries.eu/data/bhs.svg",
    name: "Bahamas",
    dialling_code: "+1",
  },
  {
    code: "BH",
    flag: "https://restcountries.eu/data/bhr.svg",
    name: "Bahrain",
    dialling_code: "+973",
  },
  {
    code: "BD",
    flag: "https://restcountries.eu/data/bgd.svg",
    name: "Bangladesh",
    dialling_code: "+880",
  },
  {
    code: "BB",
    flag: "https://restcountries.eu/data/brb.svg",
    name: "Barbados",
    dialling_code: "+1",
  },
  {
    code: "BY",
    flag: "https://restcountries.eu/data/blr.svg",
    name: "Belarus",
    dialling_code: "+375",
  },
  {
    code: "BE",
    flag: "https://restcountries.eu/data/bel.svg",
    name: "Belgium",
    dialling_code: "+32",
  },
  {
    code: "BZ",
    flag: "https://restcountries.eu/data/blz.svg",
    name: "Belize",
    dialling_code: "+501",
  },
  {
    code: "BJ",
    flag: "https://restcountries.eu/data/ben.svg",
    name: "Benin",
    dialling_code: "+229",
  },
  {
    code: "BM",
    flag: "https://restcountries.eu/data/bmu.svg",
    name: "Bermuda",
    dialling_code: "+1",
  },
  {
    code: "BT",
    flag: "https://restcountries.eu/data/btn.svg",
    name: "Bhutan",
    dialling_code: "+975",
  },
  {
    code: "BO",
    flag: "https://restcountries.eu/data/bol.svg",
    name: "Bolivia (Plurinational State of)",
    dialling_code: "+591",
  },
  {
    code: "BA",
    flag: "https://restcountries.eu/data/bih.svg",
    name: "Bosnia and Herzegovina",
    dialling_code: "+387",
  },
  {
    code: "BW",
    flag: "https://restcountries.eu/data/bwa.svg",
    name: "Botswana",
    dialling_code: "+267",
  },
  {
    code: "BR",
    flag: "https://restcountries.eu/data/bra.svg",
    name: "Brazil",
    dialling_code: "+55",
  },
  {
    code: "IO",
    flag: "https://restcountries.eu/data/iot.svg",
    name: "British Indian Ocean Territory",
    dialling_code: "+246",
  },
  {
    code: "VG",
    flag: "https://restcountries.eu/data/vgb.svg",
    name: "Virgin Islands (British)",
    dialling_code: "+1",
  },
  {
    code: "VI",
    flag: "https://restcountries.eu/data/vir.svg",
    name: "Virgin Islands (U.S.)",
    dialling_code: "+1",
  },
  {
    code: "BN",
    flag: "https://restcountries.eu/data/brn.svg",
    name: "Brunei Darussalam",
    dialling_code: "+673",
  },
  {
    code: "BG",
    flag: "https://restcountries.eu/data/bgr.svg",
    name: "Bulgaria",
    dialling_code: "+359",
  },
  {
    code: "BF",
    flag: "https://restcountries.eu/data/bfa.svg",
    name: "Burkina Faso",
    dialling_code: "+226",
  },
  {
    code: "BI",
    flag: "https://restcountries.eu/data/bdi.svg",
    name: "Burundi",
    dialling_code: "+257",
  },
  {
    code: "KH",
    flag: "https://restcountries.eu/data/khm.svg",
    name: "Cambodia",
    dialling_code: "+855",
  },
  {
    code: "CM",
    flag: "https://restcountries.eu/data/cmr.svg",
    name: "Cameroon",
    dialling_code: "+237",
  },
  {
    code: "CA",
    flag: "https://restcountries.eu/data/can.svg",
    name: "Canada",
    dialling_code: "+1",
  },
  {
    code: "CV",
    flag: "https://restcountries.eu/data/cpv.svg",
    name: "Cabo Verde",
    dialling_code: "+238",
  },
  {
    code: "KY",
    flag: "https://restcountries.eu/data/cym.svg",
    name: "Cayman Islands",
    dialling_code: "+1",
  },
  {
    code: "CF",
    flag: "https://restcountries.eu/data/caf.svg",
    name: "Central African Republic",
    dialling_code: "+236",
  },
  {
    code: "CF",
    flag: "https://restcountries.eu/data/caf.svg",
    name: "Central African Republic",
    dialling_code: "+236",
  },
  {
    code: "CL",
    flag: "https://restcountries.eu/data/chl.svg",
    name: "Chile",
    dialling_code: "+56",
  },
  {
    code: "CN",
    flag: "https://restcountries.eu/data/chn.svg",
    name: "China",
    dialling_code: "+86",
  },
  {
    code: "CO",
    flag: "https://restcountries.eu/data/col.svg",
    name: "Colombia",
    dialling_code: "+57",
  },
  {
    code: "KM",
    flag: "https://restcountries.eu/data/com.svg",
    name: "Comoros",
    dialling_code: "+269",
  },
  {
    code: "CG",
    flag: "https://restcountries.eu/data/cog.svg",
    name: "Congo",
    dialling_code: "+242",
  },
  {
    code: "CD",
    flag: "https://restcountries.eu/data/cod.svg",
    name: "Congo (Democratic Republic of the)",
    dialling_code: "+243",
  },
  {
    code: "CK",
    flag: "https://restcountries.eu/data/cok.svg",
    name: "Cook Islands",
    dialling_code: "+682",
  },
  {
    code: "CR",
    flag: "https://restcountries.eu/data/cri.svg",
    name: "Costa Rica",
    dialling_code: "+506",
  },
  {
    code: "HR",
    flag: "https://restcountries.eu/data/hrv.svg",
    name: "Croatia",
    dialling_code: "+385",
  },
  {
    code: "CU",
    flag: "https://restcountries.eu/data/cub.svg",
    name: "Cuba",
    dialling_code: "+53",
  },
  {
    code: "CU",
    flag: "https://restcountries.eu/data/cub.svg",
    name: "Cuba",
    dialling_code: "+53",
  },
  {
    code: "CY",
    flag: "https://restcountries.eu/data/cyp.svg",
    name: "Cyprus",
    dialling_code: "+357",
  },
  {
    code: "CZ",
    flag: "https://restcountries.eu/data/cze.svg",
    name: "Czech Republic",
    dialling_code: "+420",
  },
  {
    code: "DK",
    flag: "https://restcountries.eu/data/dnk.svg",
    name: "Denmark",
    dialling_code: "+45",
  },
  {
    code: "DJ",
    flag: "https://restcountries.eu/data/dji.svg",
    name: "Djibouti",
    dialling_code: "+253",
  },
  {
    code: "DM",
    flag: "https://restcountries.eu/data/dma.svg",
    name: "Dominica",
    dialling_code: "+1",
  },
  {
    code: "DO",
    flag: "https://restcountries.eu/data/dom.svg",
    name: "Dominican Republic",
    dialling_code: "+1",
  },
  {
    code: "EC",
    flag: "https://restcountries.eu/data/ecu.svg",
    name: "Ecuador",
    dialling_code: "+593",
  },
  {
    code: "EG",
    flag: "https://restcountries.eu/data/egy.svg",
    name: "Egypt",
    dialling_code: "+20",
  },
  {
    code: "SV",
    flag: "https://restcountries.eu/data/slv.svg",
    name: "El Salvador",
    dialling_code: "+503",
  },
  {
    code: "GQ",
    flag: "https://restcountries.eu/data/gnq.svg",
    name: "Equatorial Guinea",
    dialling_code: "+240",
  },
  {
    code: "ER",
    flag: "https://restcountries.eu/data/eri.svg",
    name: "Eritrea",
    dialling_code: "+291",
  },
  {
    code: "EE",
    flag: "https://restcountries.eu/data/est.svg",
    name: "Estonia",
    dialling_code: "+372",
  },
  {
    code: "ET",
    flag: "https://restcountries.eu/data/eth.svg",
    name: "Ethiopia",
    dialling_code: "+251",
  },
  {
    code: "FK",
    flag: "https://restcountries.eu/data/flk.svg",
    name: "Falkland Islands (Malvinas)",
    dialling_code: "+500",
  },
  {
    code: "FO",
    flag: "https://restcountries.eu/data/fro.svg",
    name: "Faroe Islands",
    dialling_code: "+298",
  },
  {
    code: "FJ",
    flag: "https://restcountries.eu/data/fji.svg",
    name: "Fiji",
    dialling_code: "+679",
  },
  {
    code: "FI",
    flag: "https://restcountries.eu/data/fin.svg",
    name: "Finland",
    dialling_code: "+358",
  },
  {
    code: "FR",
    flag: "https://restcountries.eu/data/fra.svg",
    name: "France",
    dialling_code: "+33",
  },
  {
    code: "GF",
    flag: "https://restcountries.eu/data/guf.svg",
    name: "French Guiana",
    dialling_code: "+594",
  },
  {
    code: "PF",
    flag: "https://restcountries.eu/data/pyf.svg",
    name: "French Polynesia",
    dialling_code: "+689",
  },
  {
    code: "GA",
    flag: "https://restcountries.eu/data/gab.svg",
    name: "Gabon",
    dialling_code: "+241",
  },
  {
    code: "GM",
    flag: "https://restcountries.eu/data/gmb.svg",
    name: "Gambia",
    dialling_code: "+220",
  },
  {
    code: "GE",
    flag: "https://restcountries.eu/data/geo.svg",
    name: "Georgia",
    dialling_code: "+995",
  },
  {
    code: "DE",
    flag: "https://restcountries.eu/data/deu.svg",
    name: "Germany",
    dialling_code: "+49",
  },
  {
    code: "GH",
    flag: "https://restcountries.eu/data/gha.svg",
    name: "Ghana",
    dialling_code: "+233",
  },
  {
    code: "GI",
    flag: "https://restcountries.eu/data/gib.svg",
    name: "Gibraltar",
    dialling_code: "+350",
  },
  {
    code: "GR",
    flag: "https://restcountries.eu/data/grc.svg",
    name: "Greece",
    dialling_code: "+30",
  },
  {
    code: "GL",
    flag: "https://restcountries.eu/data/grl.svg",
    name: "Greenland",
    dialling_code: "+299",
  },
  {
    code: "GD",
    flag: "https://restcountries.eu/data/grd.svg",
    name: "Grenada",
    dialling_code: "+1",
  },
  {
    code: "GP",
    flag: "https://restcountries.eu/data/glp.svg",
    name: "Guadeloupe",
    dialling_code: "+590",
  },
  {
    code: "GU",
    flag: "https://restcountries.eu/data/gum.svg",
    name: "Guam",
    dialling_code: "+1",
  },
  {
    code: "GT",
    flag: "https://restcountries.eu/data/gtm.svg",
    name: "Guatemala",
    dialling_code: "+502",
  },
  {
    code: "GN",
    flag: "https://restcountries.eu/data/gin.svg",
    name: "Guinea",
    dialling_code: "+224",
  },
  {
    code: "GW",
    flag: "https://restcountries.eu/data/gnb.svg",
    name: "Guinea-Bissau",
    dialling_code: "+245",
  },
  {
    code: "GY",
    flag: "https://restcountries.eu/data/guy.svg",
    name: "Guyana",
    dialling_code: "+592",
  },
  {
    code: "HT",
    flag: "https://restcountries.eu/data/hti.svg",
    name: "Haiti",
    dialling_code: "+509",
  },
  {
    code: "VA",
    flag: "https://restcountries.eu/data/vat.svg",
    name: "Holy See",
    dialling_code: "+39",
  },
  {
    code: "HN",
    flag: "https://restcountries.eu/data/hnd.svg",
    name: "Honduras",
    dialling_code: "+504",
  },
  {
    code: "HK",
    flag: "https://restcountries.eu/data/hkg.svg",
    name: "Hong Kong",
    dialling_code: "+852",
  },
  {
    code: "HU",
    flag: "https://restcountries.eu/data/hun.svg",
    name: "Hungary",
    dialling_code: "+36",
  },
  {
    code: "IS",
    flag: "https://restcountries.eu/data/isl.svg",
    name: "Iceland",
    dialling_code: "+354",
  },
  {
    code: "IN",
    flag: "https://restcountries.eu/data/ind.svg",
    name: "India",
    dialling_code: "+91",
  },
  {
    code: "ID",
    flag: "https://restcountries.eu/data/idn.svg",
    name: "Indonesia",
    dialling_code: "+62",
  },
  {
    code: "CI",
    flag: "https://restcountries.eu/data/civ.svg",
    name: "Côte d'Ivoire",
    dialling_code: "+225",
  },
  {
    code: "IR",
    flag: "https://restcountries.eu/data/irn.svg",
    name: "Iran (Islamic Republic of)",
    dialling_code: "+98",
  },
  {
    code: "IQ",
    flag: "https://restcountries.eu/data/irq.svg",
    name: "Iraq",
    dialling_code: "+964",
  },
  {
    code: "IE",
    flag: "https://restcountries.eu/data/irl.svg",
    name: "Ireland",
    dialling_code: "+353",
  },
  {
    code: "IL",
    flag: "https://restcountries.eu/data/isr.svg",
    name: "Israel",
    dialling_code: "+972",
  },
  {
    code: "IT",
    flag: "https://restcountries.eu/data/ita.svg",
    name: "Italy",
    dialling_code: "+39",
  },
  {
    code: "JM",
    flag: "https://restcountries.eu/data/jam.svg",
    name: "Jamaica",
    dialling_code: "+1",
  },
  {
    code: "JP",
    flag: "https://restcountries.eu/data/jpn.svg",
    name: "Japan",
    dialling_code: "+81",
  },
  {
    code: "JO",
    flag: "https://restcountries.eu/data/jor.svg",
    name: "Jordan",
    dialling_code: "+962",
  },
  {
    code: "KZ",
    flag: "https://restcountries.eu/data/kaz.svg",
    name: "Kazakhstan",
    dialling_code: "+7",
  },
  {
    code: "KE",
    flag: "https://restcountries.eu/data/ken.svg",
    name: "Kenya",
    dialling_code: "+254",
  },
  {
    code: "KI",
    flag: "https://restcountries.eu/data/kir.svg",
    name: "Kiribati",
    dialling_code: "+686",
  },
  {
    code: "KW",
    flag: "https://restcountries.eu/data/kwt.svg",
    name: "Kuwait",
    dialling_code: "+965",
  },
  {
    code: "KG",
    flag: "https://restcountries.eu/data/kgz.svg",
    name: "Kyrgyzstan",
    dialling_code: "+996",
  },
  {
    code: "LA",
    flag: "https://restcountries.eu/data/lao.svg",
    name: "Lao People's Democratic Republic",
    dialling_code: "+856",
  },
  {
    code: "LV",
    flag: "https://restcountries.eu/data/lva.svg",
    name: "Latvia",
    dialling_code: "+371",
  },
  {
    code: "LB",
    flag: "https://restcountries.eu/data/lbn.svg",
    name: "Lebanon",
    dialling_code: "+961",
  },
  {
    code: "LS",
    flag: "https://restcountries.eu/data/lso.svg",
    name: "Lesotho",
    dialling_code: "+266",
  },
  {
    code: "LR",
    flag: "https://restcountries.eu/data/lbr.svg",
    name: "Liberia",
    dialling_code: "+231",
  },
  {
    code: "LY",
    flag: "https://restcountries.eu/data/lby.svg",
    name: "Libya",
    dialling_code: "+218",
  },
  {
    code: "LI",
    flag: "https://restcountries.eu/data/lie.svg",
    name: "Liechtenstein",
    dialling_code: "+423",
  },
  {
    code: "LT",
    flag: "https://restcountries.eu/data/ltu.svg",
    name: "Lithuania",
    dialling_code: "+370",
  },
  {
    code: "LU",
    flag: "https://restcountries.eu/data/lux.svg",
    name: "Luxembourg",
    dialling_code: "+352",
  },
  {
    code: "MO",
    flag: "https://restcountries.eu/data/mac.svg",
    name: "Macao",
    dialling_code: "+853",
  },
  {
    code: "MK",
    flag: "https://restcountries.eu/data/mkd.svg",
    name: "Macedonia (the former Yugoslav Republic of)",
    dialling_code: "+389",
  },
  {
    code: "MG",
    flag: "https://restcountries.eu/data/mdg.svg",
    name: "Madagascar",
    dialling_code: "+261",
  },
  {
    code: "MW",
    flag: "https://restcountries.eu/data/mwi.svg",
    name: "Malawi",
    dialling_code: "+265",
  },
  {
    code: "MY",
    flag: "https://restcountries.eu/data/mys.svg",
    name: "Malaysia",
    dialling_code: "+60",
  },
  {
    code: "MV",
    flag: "https://restcountries.eu/data/mdv.svg",
    name: "Maldives",
    dialling_code: "+960",
  },
  {
    code: "ML",
    flag: "https://restcountries.eu/data/mli.svg",
    name: "Mali",
    dialling_code: "+223",
  },
  {
    code: "MT",
    flag: "https://restcountries.eu/data/mlt.svg",
    name: "Malta",
    dialling_code: "+356",
  },
  {
    code: "MH",
    flag: "https://restcountries.eu/data/mhl.svg",
    name: "Marshall Islands",
    dialling_code: "+692",
  },
  {
    code: "MQ",
    flag: "https://restcountries.eu/data/mtq.svg",
    name: "Martinique",
    dialling_code: "+596",
  },
  {
    code: "MR",
    flag: "https://restcountries.eu/data/mrt.svg",
    name: "Mauritania",
    dialling_code: "+222",
  },
  {
    code: "MU",
    flag: "https://restcountries.eu/data/mus.svg",
    name: "Mauritius",
    dialling_code: "+230",
  },
  {
    code: "YT",
    flag: "https://restcountries.eu/data/myt.svg",
    name: "Mayotte",
    dialling_code: "+262",
  },
  {
    code: "MX",
    flag: "https://restcountries.eu/data/mex.svg",
    name: "Mexico",
    dialling_code: "+52",
  },
  {
    code: "FM",
    flag: "https://restcountries.eu/data/fsm.svg",
    name: "Micronesia (Federated States of)",
    dialling_code: "+691",
  },
  {
    code: "MD",
    flag: "https://restcountries.eu/data/mda.svg",
    name: "Moldova (Republic of)",
    dialling_code: "+373",
  },
  {
    code: "MC",
    flag: "https://restcountries.eu/data/mco.svg",
    name: "Monaco",
    dialling_code: "+377",
  },
  {
    code: "MN",
    flag: "https://restcountries.eu/data/mng.svg",
    name: "Mongolia",
    dialling_code: "+976",
  },
  {
    code: "ME",
    flag: "https://restcountries.eu/data/mne.svg",
    name: "Montenegro",
    dialling_code: "+382",
  },
  {
    code: "MS",
    flag: "https://restcountries.eu/data/msr.svg",
    name: "Montserrat",
    dialling_code: "+1",
  },
  {
    code: "MA",
    flag: "https://restcountries.eu/data/mar.svg",
    name: "Morocco",
    dialling_code: "+212",
  },
  {
    code: "MZ",
    flag: "https://restcountries.eu/data/moz.svg",
    name: "Mozambique",
    dialling_code: "+258",
  },
  {
    code: "MM",
    flag: "https://restcountries.eu/data/mmr.svg",
    name: "Myanmar",
    dialling_code: "+95",
  },
  {
    code: "NA",
    flag: "https://restcountries.eu/data/nam.svg",
    name: "Namibia",
    dialling_code: "+264",
  },
  {
    code: "NR",
    flag: "https://restcountries.eu/data/nru.svg",
    name: "Nauru",
    dialling_code: "+674",
  },
  {
    code: "NP",
    flag: "https://restcountries.eu/data/npl.svg",
    name: "Nepal",
    dialling_code: "+977",
  },
  {
    code: "NL",
    flag: "https://restcountries.eu/data/nld.svg",
    name: "Netherlands",
    dialling_code: "+31",
  },
  {
    code: "NC",
    flag: "https://restcountries.eu/data/ncl.svg",
    name: "New Caledonia",
    dialling_code: "+687",
  },
  {
    code: "NZ",
    flag: "https://restcountries.eu/data/nzl.svg",
    name: "New Zealand",
    dialling_code: "+64",
  },
  {
    code: "NI",
    flag: "https://restcountries.eu/data/nic.svg",
    name: "Nicaragua",
    dialling_code: "+505",
  },
  {
    code: "NE",
    flag: "https://restcountries.eu/data/ner.svg",
    name: "Niger",
    dialling_code: "+227",
  },
  {
    code: "NG",
    flag: "https://restcountries.eu/data/nga.svg",
    name: "Nigeria",
    dialling_code: "+234",
  },
  {
    code: "NU",
    flag: "https://restcountries.eu/data/niu.svg",
    name: "Niue",
    dialling_code: "+683",
  },
  {
    code: "NF",
    flag: "https://restcountries.eu/data/nfk.svg",
    name: "Norfolk Island",
    dialling_code: "+672",
  },
  {
    code: "KP",
    flag: "https://restcountries.eu/data/prk.svg",
    name: "Korea (Democratic People's Republic of)",
    dialling_code: "+850",
  },
  {
    code: "MP",
    flag: "https://restcountries.eu/data/mnp.svg",
    name: "Northern Mariana Islands",
    dialling_code: "+1",
  },
  {
    code: "NO",
    flag: "https://restcountries.eu/data/nor.svg",
    name: "Norway",
    dialling_code: "+47",
  },
  {
    code: "OM",
    flag: "https://restcountries.eu/data/omn.svg",
    name: "Oman",
    dialling_code: "+968",
  },
  {
    code: "PK",
    flag: "https://restcountries.eu/data/pak.svg",
    name: "Pakistan",
    dialling_code: "+92",
  },
  {
    code: "PW",
    flag: "https://restcountries.eu/data/plw.svg",
    name: "Palau",
    dialling_code: "+680",
  },
  {
    code: "PS",
    flag: "https://restcountries.eu/data/pse.svg",
    name: "Palestine, State of",
    dialling_code: "+970",
  },
  {
    code: "PA",
    flag: "https://restcountries.eu/data/pan.svg",
    name: "Panama",
    dialling_code: "+507",
  },
  {
    code: "PG",
    flag: "https://restcountries.eu/data/png.svg",
    name: "Papua New Guinea",
    dialling_code: "+675",
  },
  {
    code: "PY",
    flag: "https://restcountries.eu/data/pry.svg",
    name: "Paraguay",
    dialling_code: "+595",
  },
  {
    code: "PE",
    flag: "https://restcountries.eu/data/per.svg",
    name: "Peru",
    dialling_code: "+51",
  },
  {
    code: "PH",
    flag: "https://restcountries.eu/data/phl.svg",
    name: "Philippines",
    dialling_code: "+63",
  },
  {
    code: "PL",
    flag: "https://restcountries.eu/data/pol.svg",
    name: "Poland",
    dialling_code: "+48",
  },
  {
    code: "PT",
    flag: "https://restcountries.eu/data/prt.svg",
    name: "Portugal",
    dialling_code: "+351",
  },
  {
    code: "PR",
    flag: "https://restcountries.eu/data/pri.svg",
    name: "Puerto Rico",
    dialling_code: "+1",
  },
  {
    code: "QA",
    flag: "https://restcountries.eu/data/qat.svg",
    name: "Qatar",
    dialling_code: "+974",
  },
  {
    code: "XK",
    flag: "https://restcountries.eu/data/kos.svg",
    name: "Republic of Kosovo",
    dialling_code: "+381",
  },
  {
    code: "RE",
    flag: "https://restcountries.eu/data/reu.svg",
    name: "Réunion",
    dialling_code: "+262",
  },
  {
    code: "RO",
    flag: "https://restcountries.eu/data/rou.svg",
    name: "Romania",
    dialling_code: "+40",
  },
  {
    code: "RU",
    flag: "https://restcountries.eu/data/rus.svg",
    name: "Russian Federation",
    dialling_code: "+7",
  },
  {
    code: "RW",
    flag: "https://restcountries.eu/data/rwa.svg",
    name: "Rwanda",
    dialling_code: "+250",
  },
  {
    code: "BL",
    flag: "https://restcountries.eu/data/blm.svg",
    name: "Saint Barthélemy",
    dialling_code: "+590",
  },
  {
    code: "SH",
    flag: "https://restcountries.eu/data/shn.svg",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    dialling_code: "+290",
  },
  {
    code: "KN",
    flag: "https://restcountries.eu/data/kna.svg",
    name: "Saint Kitts and Nevis",
    dialling_code: "+1",
  },
  {
    code: "LC",
    flag: "https://restcountries.eu/data/lca.svg",
    name: "Saint Lucia",
    dialling_code: "+1",
  },
  {
    code: "MF",
    flag: "https://restcountries.eu/data/maf.svg",
    name: "Saint Martin (French part)",
    dialling_code: "+590",
  },
  {
    code: "PM",
    flag: "https://restcountries.eu/data/spm.svg",
    name: "Saint Pierre and Miquelon",
    dialling_code: "+508",
  },
  {
    code: "VC",
    flag: "https://restcountries.eu/data/vct.svg",
    name: "Saint Vincent and the Grenadines",
    dialling_code: "+1",
  },
  {
    code: "WS",
    flag: "https://restcountries.eu/data/wsm.svg",
    name: "Samoa",
    dialling_code: "+685",
  },
  {
    code: "SM",
    flag: "https://restcountries.eu/data/smr.svg",
    name: "San Marino",
    dialling_code: "+378",
  },
  {
    code: "ST",
    flag: "https://restcountries.eu/data/stp.svg",
    name: "Sao Tome and Principe",
    dialling_code: "+239",
  },
  {
    code: "SA",
    flag: "https://restcountries.eu/data/sau.svg",
    name: "Saudi Arabia",
    dialling_code: "+966",
  },
  {
    code: "SN",
    flag: "https://restcountries.eu/data/sen.svg",
    name: "Senegal",
    dialling_code: "+221",
  },
  {
    code: "RS",
    flag: "https://restcountries.eu/data/srb.svg",
    name: "Serbia",
    dialling_code: "+381",
  },
  {
    code: "SC",
    flag: "https://restcountries.eu/data/syc.svg",
    name: "Seychelles",
    dialling_code: "+248",
  },
  {
    code: "SL",
    flag: "https://restcountries.eu/data/sle.svg",
    name: "Sierra Leone",
    dialling_code: "+232",
  },
  {
    code: "SG",
    flag: "https://restcountries.eu/data/sgp.svg",
    name: "Singapore",
    dialling_code: "+65",
  },
  {
    code: "SG",
    flag: "https://restcountries.eu/data/sgp.svg",
    name: "Singapore",
    dialling_code: "+65",
  },
  {
    code: "SK",
    flag: "https://restcountries.eu/data/svk.svg",
    name: "Slovakia",
    dialling_code: "+421",
  },
  {
    code: "SI",
    flag: "https://restcountries.eu/data/svn.svg",
    name: "Slovenia",
    dialling_code: "+386",
  },
  {
    code: "SB",
    flag: "https://restcountries.eu/data/slb.svg",
    name: "Solomon Islands",
    dialling_code: "+677",
  },
  {
    code: "SO",
    flag: "https://restcountries.eu/data/som.svg",
    name: "Somalia",
    dialling_code: "+252",
  },
  {
    code: "ZA",
    flag: "https://restcountries.eu/data/zaf.svg",
    name: "South Africa",
    dialling_code: "+27",
  },
  {
    code: "KR",
    flag: "https://restcountries.eu/data/kor.svg",
    name: "Korea (Republic of)",
    dialling_code: "+82",
  },
  {
    code: "ES",
    flag: "https://restcountries.eu/data/esp.svg",
    name: "Spain",
    dialling_code: "+34",
  },
  {
    code: "LK",
    flag: "https://restcountries.eu/data/lka.svg",
    name: "Sri Lanka",
    dialling_code: "+94",
  },
  {
    code: "SD",
    flag: "https://restcountries.eu/data/sdn.svg",
    name: "Sudan",
    dialling_code: "+249",
  },
  {
    code: "SR",
    flag: "https://restcountries.eu/data/sur.svg",
    name: "Suriname",
    dialling_code: "+597",
  },
  {
    code: "SZ",
    flag: "https://restcountries.eu/data/swz.svg",
    name: "Swaziland",
    dialling_code: "+268",
  },
  {
    code: "SE",
    flag: "https://restcountries.eu/data/swe.svg",
    name: "Sweden",
    dialling_code: "+46",
  },
  {
    code: "CH",
    flag: "https://restcountries.eu/data/che.svg",
    name: "Switzerland",
    dialling_code: "+41",
  },
  {
    code: "SY",
    flag: "https://restcountries.eu/data/syr.svg",
    name: "Syrian Arab Republic",
    dialling_code: "+963",
  },
  {
    code: "TW",
    flag: "https://restcountries.eu/data/twn.svg",
    name: "Taiwan",
    dialling_code: "+886",
  },
  {
    code: "TJ",
    flag: "https://restcountries.eu/data/tjk.svg",
    name: "Tajikistan",
    dialling_code: "+992",
  },
  {
    code: "TZ",
    flag: "https://restcountries.eu/data/tza.svg",
    name: "Tanzania, United Republic of",
    dialling_code: "+255",
  },
  {
    code: "TH",
    flag: "https://restcountries.eu/data/tha.svg",
    name: "Thailand",
    dialling_code: "+66",
  },
  {
    code: "TL",
    flag: "https://restcountries.eu/data/tls.svg",
    name: "Timor-Leste",
    dialling_code: "+670",
  },
  {
    code: "TG",
    flag: "https://restcountries.eu/data/tgo.svg",
    name: "Togo",
    dialling_code: "+228",
  },
  {
    code: "TK",
    flag: "https://restcountries.eu/data/tkl.svg",
    name: "Tokelau",
    dialling_code: "+690",
  },
  {
    code: "TO",
    flag: "https://restcountries.eu/data/ton.svg",
    name: "Tonga",
    dialling_code: "+676",
  },
  {
    code: "TT",
    flag: "https://restcountries.eu/data/tto.svg",
    name: "Trinidad and Tobago",
    dialling_code: "+1",
  },
  {
    code: "TN",
    flag: "https://restcountries.eu/data/tun.svg",
    name: "Tunisia",
    dialling_code: "+216",
  },
  {
    code: "TR",
    flag: "https://restcountries.eu/data/tur.svg",
    name: "Turkey",
    dialling_code: "+90",
  },
  {
    code: "TM",
    flag: "https://restcountries.eu/data/tkm.svg",
    name: "Turkmenistan",
    dialling_code: "+993",
  },
  {
    code: "TC",
    flag: "https://restcountries.eu/data/tca.svg",
    name: "Turks and Caicos Islands",
    dialling_code: "+1",
  },
  {
    code: "TV",
    flag: "https://restcountries.eu/data/tuv.svg",
    name: "Tuvalu",
    dialling_code: "+688",
  },
  {
    code: "UG",
    flag: "https://restcountries.eu/data/uga.svg",
    name: "Uganda",
    dialling_code: "+256",
  },
  {
    code: "UA",
    flag: "https://restcountries.eu/data/ukr.svg",
    name: "Ukraine",
    dialling_code: "+380",
  },
  {
    code: "AE",
    flag: "https://restcountries.eu/data/are.svg",
    name: "United Arab Emirates",
    dialling_code: "+971",
  },
  {
    code: "GB",
    flag: "https://restcountries.eu/data/gbr.svg",
    name: "United Kingdom of Great Britain and Northern Ireland",
    dialling_code: "+44",
  },
  {
    code: "US",
    flag: "https://restcountries.eu/data/usa.svg",
    name: "United States of America",
    dialling_code: "+1",
  },
  {
    code: "UY",
    flag: "https://restcountries.eu/data/ury.svg",
    name: "Uruguay",
    dialling_code: "+598",
  },
  {
    code: "UZ",
    flag: "https://restcountries.eu/data/uzb.svg",
    name: "Uzbekistan",
    dialling_code: "+998",
  },
  {
    code: "VU",
    flag: "https://restcountries.eu/data/vut.svg",
    name: "Vanuatu",
    dialling_code: "+678",
  },
  {
    code: "VE",
    flag: "https://restcountries.eu/data/ven.svg",
    name: "Venezuela (Bolivarian Republic of)",
    dialling_code: "+58",
  },
  {
    code: "VN",
    flag: "https://restcountries.eu/data/vnm.svg",
    name: "Viet Nam",
    dialling_code: "+84",
  },
  {
    code: "WF",
    flag: "https://restcountries.eu/data/wlf.svg",
    name: "Wallis and Futuna",
    dialling_code: "+681",
  },
  {
    code: "WF",
    flag: "https://restcountries.eu/data/wlf.svg",
    name: "Wallis and Futuna",
    dialling_code: "+681",
  },
  {
    code: "YE",
    flag: "https://restcountries.eu/data/yem.svg",
    name: "Yemen",
    dialling_code: "+967",
  },
  {
    code: "ZM",
    flag: "https://restcountries.eu/data/zmb.svg",
    name: "Zambia",
    dialling_code: "+260",
  },
  {
    code: "ZW",
    flag: "https://restcountries.eu/data/zwe.svg",
    name: "Zimbabwe",
    dialling_code: "+263",
  },
];
